/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ImportantQuestion {
  'subject' : string,
  'questions' : Array<string>,
  'chapter' : string,
  'classNum' : bigint,
}
export interface MCQ {
  'subject' : string,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'chapter' : string,
  'options' : Array<string>,
}
export interface Note {
  'subject' : string,
  'keyPoints' : Array<string>,
  'chapter' : string,
  'classNum' : bigint,
}
export interface Solution {
  'question' : string,
  'subject' : string,
  'answer' : string,
  'chapter' : string,
  'classNum' : bigint,
}
export interface _SERVICE {
  'addImportantQuestions' : ActorMethod<[bigint, ImportantQuestion], undefined>,
  'addMCQ' : ActorMethod<[bigint, MCQ], undefined>,
  'addNote' : ActorMethod<[bigint, Note], undefined>,
  'addSolution' : ActorMethod<[bigint, Solution], undefined>,
  'getAllImportantQuestions' : ActorMethod<[], Array<ImportantQuestion>>,
  'getAllMCQs' : ActorMethod<[], Array<MCQ>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllSolutions' : ActorMethod<[], Array<Solution>>,
  'searchByKeyword' : ActorMethod<
    [string],
    [Array<MCQ>, Array<Note>, Array<Solution>, Array<ImportantQuestion>]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];