/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ImportantQuestion = IDL.Record({
  'subject' : IDL.Text,
  'questions' : IDL.Vec(IDL.Text),
  'chapter' : IDL.Text,
  'classNum' : IDL.Nat,
});
export const MCQ = IDL.Record({
  'subject' : IDL.Text,
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'chapter' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const Note = IDL.Record({
  'subject' : IDL.Text,
  'keyPoints' : IDL.Vec(IDL.Text),
  'chapter' : IDL.Text,
  'classNum' : IDL.Nat,
});
export const Solution = IDL.Record({
  'question' : IDL.Text,
  'subject' : IDL.Text,
  'answer' : IDL.Text,
  'chapter' : IDL.Text,
  'classNum' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addImportantQuestions' : IDL.Func([IDL.Nat, ImportantQuestion], [], []),
  'addMCQ' : IDL.Func([IDL.Nat, MCQ], [], []),
  'addNote' : IDL.Func([IDL.Nat, Note], [], []),
  'addSolution' : IDL.Func([IDL.Nat, Solution], [], []),
  'getAllImportantQuestions' : IDL.Func(
      [],
      [IDL.Vec(ImportantQuestion)],
      ['query'],
    ),
  'getAllMCQs' : IDL.Func([], [IDL.Vec(MCQ)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllSolutions' : IDL.Func([], [IDL.Vec(Solution)], ['query']),
  'searchByKeyword' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(MCQ),
        IDL.Vec(Note),
        IDL.Vec(Solution),
        IDL.Vec(ImportantQuestion),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ImportantQuestion = IDL.Record({
    'subject' : IDL.Text,
    'questions' : IDL.Vec(IDL.Text),
    'chapter' : IDL.Text,
    'classNum' : IDL.Nat,
  });
  const MCQ = IDL.Record({
    'subject' : IDL.Text,
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'chapter' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const Note = IDL.Record({
    'subject' : IDL.Text,
    'keyPoints' : IDL.Vec(IDL.Text),
    'chapter' : IDL.Text,
    'classNum' : IDL.Nat,
  });
  const Solution = IDL.Record({
    'question' : IDL.Text,
    'subject' : IDL.Text,
    'answer' : IDL.Text,
    'chapter' : IDL.Text,
    'classNum' : IDL.Nat,
  });
  
  return IDL.Service({
    'addImportantQuestions' : IDL.Func([IDL.Nat, ImportantQuestion], [], []),
    'addMCQ' : IDL.Func([IDL.Nat, MCQ], [], []),
    'addNote' : IDL.Func([IDL.Nat, Note], [], []),
    'addSolution' : IDL.Func([IDL.Nat, Solution], [], []),
    'getAllImportantQuestions' : IDL.Func(
        [],
        [IDL.Vec(ImportantQuestion)],
        ['query'],
      ),
    'getAllMCQs' : IDL.Func([], [IDL.Vec(MCQ)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllSolutions' : IDL.Func([], [IDL.Vec(Solution)], ['query']),
    'searchByKeyword' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(MCQ),
          IDL.Vec(Note),
          IDL.Vec(Solution),
          IDL.Vec(ImportantQuestion),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };