/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MCQ {
    subject: string;
    questionText: string;
    correctAnswerIndex: bigint;
    chapter: string;
    options: Array<string>;
}
export interface Solution {
    question: string;
    subject: string;
    answer: string;
    chapter: string;
    classNum: bigint;
}
export interface ImportantQuestion {
    subject: string;
    questions: Array<string>;
    chapter: string;
    classNum: bigint;
}
export interface Note {
    subject: string;
    keyPoints: Array<string>;
    chapter: string;
    classNum: bigint;
}
export interface backendInterface {
    addImportantQuestions(id: bigint, importantQuestion: ImportantQuestion): Promise<void>;
    addMCQ(id: bigint, mcq: MCQ): Promise<void>;
    addNote(id: bigint, note: Note): Promise<void>;
    addSolution(id: bigint, solution: Solution): Promise<void>;
    getAllImportantQuestions(): Promise<Array<ImportantQuestion>>;
    getAllMCQs(): Promise<Array<MCQ>>;
    getAllNotes(): Promise<Array<Note>>;
    getAllSolutions(): Promise<Array<Solution>>;
    searchByKeyword(keyword: string): Promise<[Array<MCQ>, Array<Note>, Array<Solution>, Array<ImportantQuestion>]>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addImportantQuestions(arg0: bigint, arg1: ImportantQuestion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addImportantQuestions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImportantQuestions(arg0, arg1);
            return result;
        }
    }
    async addMCQ(arg0: bigint, arg1: MCQ): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMCQ(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMCQ(arg0, arg1);
            return result;
        }
    }
    async addNote(arg0: bigint, arg1: Note): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, arg1);
            return result;
        }
    }
    async addSolution(arg0: bigint, arg1: Solution): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSolution(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSolution(arg0, arg1);
            return result;
        }
    }
    async getAllImportantQuestions(): Promise<Array<ImportantQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImportantQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImportantQuestions();
            return result;
        }
    }
    async getAllMCQs(): Promise<Array<MCQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMCQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMCQs();
            return result;
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return result;
        }
    }
    async getAllSolutions(): Promise<Array<Solution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSolutions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSolutions();
            return result;
        }
    }
    async searchByKeyword(arg0: string): Promise<[Array<MCQ>, Array<Note>, Array<Solution>, Array<ImportantQuestion>]> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByKeyword(arg0);
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByKeyword(arg0);
            return [
                result[0],
                result[1],
                result[2],
                result[3]
            ];
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
